language: node_js

node_js:
 - "node"

cache: npm

install:
  - npm install -g codecov

script:
  - npm run build
  - npm run test:unit

after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  local_dir: dist

